### ISSUE TITLE
Create Project Plan

### ISSUE THREAD

**Issue by NguyenThienBao** [NguyenThienBao/se-capstone-project#1]
Get information of project and Create project plan document.

1. Kick-off meeting with client.
2. Get Draft requirement.
3. Create project plan document.

**Comment by NguyenThienBao** [comment]
Kick-off meeting with client - Meeting note

> Requirements
>> 1. Build a online e-commerce for selling toys and teddy bears for children.
>> 2. The system can support online payment for Vietnamese Market.
>> 3. The client can monitor real-time sale statistics and get report for sales.

> Time-line for project is 1 month.

> Technical request is NONE.

**Comment by NguyenThienBao** [comment]
@NguyenThienBao Create Project Plan.

- [x] Search and Create template for Project Plan.
- [x] Create Project Plan Document with project information.
- [x] Present with team and Public.

**Comment by NguyenThienBao** [comment]
Using document template from https://sceweb.sce.uhcl.edu/helm/RUP_Folder/RationalUnifiedProcess/process/templates.htm
